### ISSUE TITLE
ログファイルが存在しない

### ISSUE THREAD

**Issue by stu2005** [gcch/Chinachu-Mirakurun-SS#1]
Raspbian Buster に mirakurun 12.13.0 と chinachu gammaを入れた環境にてこちらのスクリプトを導入しましたが、/var/log/chinachu-mirakurun-ss.log が存在していないようです。よって、ログが確認できません。また、インストール時にcrondを再起動できないエラーが出ていました。(手動で再起動しました)　バグかどうかはわかりませんがお力をお貸しください。

**Comment by gcch** [comment]
/var/log/chinachu-mirakurun-ss.log ですが、cron での定時処理実行タイミングで出力されるログファイルになっています。

Raspbian Buster ではありませんが、一つ前の Raspbian Stretch 環境で試してみたところ、crontab ファイルの構文エラーにより実行対象外となっていることが確認できました。
同事象であるかは以下のコマンドを実行いただき、
```
$ sudo systemctl restart cron
$ sudo systemctl status cron
```
後半に出力されている cron のログメッセージに
```
Error: bad username; while reading /etc/cron.d/chinachu-mirakurun-ss-cron
```
や
```
(*system*chinachu-mirakurun-ss-cron) ERROR (Syntax error, this crontab file will be ignored)
```
といったメッセージが表示されていれば同事象と思われます。

本事象に対し、[chinachu-mirakurun-ss-cron](../blob/master/main/cron/chinachu-mirakurun-ss-cron) の修正を行いましたので、Chianchu-Mirakurun-SS の再取得の後、インストールをお願いします。
また、インストール時にサービス再起動されない事象についても [install.sh](../blob/master/main/install.sh) を修正していますので、合わせて状況を確認いただければと思います。

**Comment by stu2005** [comment]
同事象であること、修正されていることを確認しました。対応ありがとうございます。
